export const appliances: {
  appliance: string;
  consumption_kwh: number;
  size: "big" | "medium" | "small";
}[] = [
  { "appliance": "Refrigerator", "consumption_kwh": 150, "size": "big" },
  { "appliance": "Washing Machine", "consumption_kwh": 0.3, "size": "medium" },
  { "appliance": "Dryer", "consumption_kwh": 3.3, "size": "big" },
  { "appliance": "Dishwasher", "consumption_kwh": 1.5, "size": "medium" },
  { "appliance": "Microwave", "consumption_kwh": 1.2, "size": "small" },
  { "appliance": "Toaster", "consumption_kwh": 0.7, "size": "small" },
  { "appliance": "Coffee Maker", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Blender", "consumption_kwh": 0.4, "size": "small" },
  { "appliance": "Oven", "consumption_kwh": 2.0, "size": "big" },
  { "appliance": "Stove", "consumption_kwh": 1.5, "size": "big" },
  { "appliance": "Electric Kettle", "consumption_kwh": 1.5, "size": "small" },
  { "appliance": "Air Conditioner", "consumption_kwh": 1.5, "size": "big" },
  { "appliance": "Heater", "consumption_kwh": 1.8, "size": "big" },
  { "appliance": "Ceiling Fan", "consumption_kwh": 0.05, "size": "medium" },
  { "appliance": "Space Heater", "consumption_kwh": 1.2, "size": "small" },
  { "appliance": "TV (LED)", "consumption_kwh": 0.1, "size": "medium" },
  { "appliance": "Computer", "consumption_kwh": 0.15, "size": "small" },
  { "appliance": "Laptop", "consumption_kwh": 0.05, "size": "small" },
  { "appliance": "Printer", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Router", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Game Console", "consumption_kwh": 0.15, "size": "small" },
  { "appliance": "Iron", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Hair Dryer", "consumption_kwh": 0.8, "size": "small" },
  { "appliance": "Vacuum Cleaner", "consumption_kwh": 0.7, "size": "medium" },
  { "appliance": "Humidifier", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Dehumidifier", "consumption_kwh": 0.5, "size": "medium" },
  { "appliance": "Fan", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Water Heater", "consumption_kwh": 4.0, "size": "big" },
  { "appliance": "Chest Freezer", "consumption_kwh": 200, "size": "big" },
  { "appliance": "Electric Blanket", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Alarm Clock", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Smoke Detector", "consumption_kwh": 0.001, "size": "small" },
  { "appliance": "Air Purifier", "consumption_kwh": 0.05, "size": "small" },
  {
    "appliance": "Rechargeable Battery Charger",
    "consumption_kwh": 0.02,
    "size": "small",
  },
  { "appliance": "Electric Shaver", "consumption_kwh": 0.02, "size": "small" },
  {
    "appliance": "Electric Toothbrush",
    "consumption_kwh": 0.01,
    "size": "small",
  },
  { "appliance": "Hair Straightener", "consumption_kwh": 0.5, "size": "small" },
  {
    "appliance": "Smartphone Charger",
    "consumption_kwh": 0.01,
    "size": "small",
  },
  {
    "appliance": "Electric Can Opener",
    "consumption_kwh": 0.05,
    "size": "small",
  },
  { "appliance": "Garbage Disposal", "consumption_kwh": 0.5, "size": "small" },
  { "appliance": "Food Processor", "consumption_kwh": 0.2, "size": "small" },
  { "appliance": "Electric Grill", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Sewing Machine", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Electric Mixer", "consumption_kwh": 0.3, "size": "small" },
  { "appliance": "Clock", "consumption_kwh": 0.01, "size": "small" },
  { "appliance": "Food Steamer", "consumption_kwh": 0.5, "size": "small" },
  { "appliance": "Air Fryer", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Rice Cooker", "consumption_kwh": 0.3, "size": "small" },
  { "appliance": "Electric Blanket", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Alarm Clock", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Smoke Detector", "consumption_kwh": 0.001, "size": "small" },
  { "appliance": "Air Purifier", "consumption_kwh": 0.05, "size": "small" },
  { "appliance": "Rechargeable Battery Charger", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Electric Shaver", "consumption_kwh": 0.02, "size": "small" },
  { "appliance": "Electric Toothbrush", "consumption_kwh": 0.01, "size": "small" },
  { "appliance": "Hair Straightener", "consumption_kwh": 0.5, "size": "small" },
  { "appliance": "Smartphone Charger", "consumption_kwh": 0.01, "size": "small" },
  { "appliance": "Electric Can Opener", "consumption_kwh": 0.05, "size": "small" },
  { "appliance": "Garbage Disposal", "consumption_kwh": 0.5, "size": "small" },
  { "appliance": "Food Processor", "consumption_kwh": 0.2, "size": "small" },
  { "appliance": "Electric Grill", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Sewing Machine", "consumption_kwh": 0.1, "size": "small" },
  { "appliance": "Electric Mixer", "consumption_kwh": 0.3, "size": "small" },
  { "appliance": "Clock", "consumption_kwh": 0.01, "size": "small" },
  { "appliance": "Food Steamer", "consumption_kwh": 0.5, "size": "small" },
  { "appliance": "Air Fryer", "consumption_kwh": 1.0, "size": "small" },
  { "appliance": "Rice Cooker", "consumption_kwh": 0.3, "size": "small" },
];
